// Generated by gencpp from file drive_ros_msgs/EncoderLinear.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_ENCODERLINEAR_H
#define DRIVE_ROS_MSGS_MESSAGE_ENCODERLINEAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct EncoderLinear_
{
  typedef EncoderLinear_<ContainerAllocator> Type;

  EncoderLinear_()
    : header()
    , pos_abs(0.0)
    , pos_abs_var(0.0)
    , pos_rel(0.0)
    , pos_rel_var(0.0)
    , vel(0.0)
    , vel_var(0.0)  {
    }
  EncoderLinear_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos_abs(0.0)
    , pos_abs_var(0.0)
    , pos_rel(0.0)
    , pos_rel_var(0.0)
    , vel(0.0)
    , vel_var(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pos_abs_type;
  _pos_abs_type pos_abs;

   typedef float _pos_abs_var_type;
  _pos_abs_var_type pos_abs_var;

   typedef float _pos_rel_type;
  _pos_rel_type pos_rel;

   typedef float _pos_rel_var_type;
  _pos_rel_var_type pos_rel_var;

   typedef float _vel_type;
  _vel_type vel;

   typedef float _vel_var_type;
  _vel_var_type vel_var;




  typedef boost::shared_ptr< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> const> ConstPtr;

}; // struct EncoderLinear_

typedef ::drive_ros_msgs::EncoderLinear_<std::allocator<void> > EncoderLinear;

typedef boost::shared_ptr< ::drive_ros_msgs::EncoderLinear > EncoderLinearPtr;
typedef boost::shared_ptr< ::drive_ros_msgs::EncoderLinear const> EncoderLinearConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c78bee85271f30efdc5b5221778b0109";
  }

  static const char* value(const ::drive_ros_msgs::EncoderLinear_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc78bee85271f30efULL;
  static const uint64_t static_value2 = 0xdc5b5221778b0109ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/EncoderLinear";
  }

  static const char* value(const ::drive_ros_msgs::EncoderLinear_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# linear encoder message\n\
Header header\n\
\n\
# absolut position of encoder in [m]\n\
float32 pos_abs\n\
float32 pos_abs_var\n\
\n\
# relative position of encoder in [m] compared to last message\n\
float32 pos_rel\n\
float32 pos_rel_var\n\
\n\
# velocity of encoder in [m/s]\n\
float32 vel\n\
float32 vel_var\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drive_ros_msgs::EncoderLinear_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos_abs);
      stream.next(m.pos_abs_var);
      stream.next(m.pos_rel);
      stream.next(m.pos_rel_var);
      stream.next(m.vel);
      stream.next(m.vel_var);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncoderLinear_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::EncoderLinear_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::EncoderLinear_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos_abs: ";
    Printer<float>::stream(s, indent + "  ", v.pos_abs);
    s << indent << "pos_abs_var: ";
    Printer<float>::stream(s, indent + "  ", v.pos_abs_var);
    s << indent << "pos_rel: ";
    Printer<float>::stream(s, indent + "  ", v.pos_rel);
    s << indent << "pos_rel_var: ";
    Printer<float>::stream(s, indent + "  ", v.pos_rel_var);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "vel_var: ";
    Printer<float>::stream(s, indent + "  ", v.vel_var);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_ENCODERLINEAR_H
