// Generated by gencpp from file drive_ros_msgs/mav_cc16_HEARTBEAT.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_HEARTBEAT_H
#define DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_HEARTBEAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct mav_cc16_HEARTBEAT_
{
  typedef mav_cc16_HEARTBEAT_<ContainerAllocator> Type;

  mav_cc16_HEARTBEAT_()
    : header()
    , sysid(0)
    , compid(0)
    , battery_voltage(0)
    , remote_control(0)
    , drive_mode(0)
    , rc_velocity(0.0)
    , rc_steering_front(0.0)
    , rc_steering_rear(0.0)  {
    }
  mav_cc16_HEARTBEAT_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sysid(0)
    , compid(0)
    , battery_voltage(0)
    , remote_control(0)
    , drive_mode(0)
    , rc_velocity(0.0)
    , rc_steering_front(0.0)
    , rc_steering_rear(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint16_t _battery_voltage_type;
  _battery_voltage_type battery_voltage;

   typedef uint8_t _remote_control_type;
  _remote_control_type remote_control;

   typedef uint8_t _drive_mode_type;
  _drive_mode_type drive_mode;

   typedef float _rc_velocity_type;
  _rc_velocity_type rc_velocity;

   typedef float _rc_steering_front_type;
  _rc_steering_front_type rc_steering_front;

   typedef float _rc_steering_rear_type;
  _rc_steering_rear_type rc_steering_rear;


    enum { ID = 1u };
     enum { REMOTE_CONTROL_STATUS_DISCONNECTED = 0u };
     enum { REMOTE_CONTROL_STATUS_CONNECTED = 1u };
     enum { REMOTE_CONTROL_STATUS_AUTONOMOUS = 2u };
     enum { REMOTE_CONTROL_STATUS_SEMI_AUTONOMOUS = 3u };
     enum { REMOTE_CONTROL_STATUS_MANUAL = 4u };
     enum { DRIVE_MODE_TRACK = 0u };
     enum { DRIVE_MODE_TRACK_OBSTACLES = 1u };
     enum { DRIVE_MODE_PARKING = 2u };
     enum { DRIVE_MODE_IDLE = 3u };
 

  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> const> ConstPtr;

}; // struct mav_cc16_HEARTBEAT_

typedef ::drive_ros_msgs::mav_cc16_HEARTBEAT_<std::allocator<void> > mav_cc16_HEARTBEAT;

typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_HEARTBEAT > mav_cc16_HEARTBEATPtr;
typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_HEARTBEAT const> mav_cc16_HEARTBEATConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f0c43a59dc6fe6c5ede5ec59a47ab1b";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f0c43a59dc6fe6cULL;
  static const uint64_t static_value2 = 0x5ede5ec59a47ab1bULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/mav_cc16_HEARTBEAT";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2017-06-12 22:33:47.452693\n\
# MESSAGE: HEARTBEAT\n\
# Description:Heartbeat status message\n\
Header header\n\
\n\
uint8 ID = 1\n\
uint8 sysid\n\
uint8 compid\n\
\n\
uint16 battery_voltage      # Battery voltage, in millivolts (1 = 1 millivolt)\n\
uint8 remote_control        # Remote Control status (see REMOTE_CONTROL_STATUS ENUM)\n\
uint8 drive_mode            # Selected drive mode (see DRIVE_MODE ENUM)\n\
float32 rc_velocity         # Velocity set by remote control [m/s]\n\
float32 rc_steering_front   # Front steering angle set by remote control [rad]\n\
float32 rc_steering_rear    # Rear steering angle set by remote control [rad]\n\
\n\
uint8 REMOTE_CONTROL_STATUS_DISCONNECTED = 0     # Remote Control is not connected to the system\n\
uint8 REMOTE_CONTROL_STATUS_CONNECTED = 1        # Remote Control connection is established\n\
uint8 REMOTE_CONTROL_STATUS_AUTONOMOUS = 2       # Remote Control is connected and under active control\n\
uint8 REMOTE_CONTROL_STATUS_SEMI_AUTONOMOUS = 3  # Remote Control is connected and under active control\n\
uint8 REMOTE_CONTROL_STATUS_MANUAL = 4           # Remote Control is connected and under active control\n\
\n\
\n\
uint8 DRIVE_MODE_TRACK = 0              # Track (excluding obstacles)\n\
uint8 DRIVE_MODE_TRACK_OBSTACLES = 1    # Track including obstacles\n\
uint8 DRIVE_MODE_PARKING = 2            # Parking mode\n\
uint8 DRIVE_MODE_IDLE = 3               # Idle mode\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.battery_voltage);
      stream.next(m.remote_control);
      stream.next(m.drive_mode);
      stream.next(m.rc_velocity);
      stream.next(m.rc_steering_front);
      stream.next(m.rc_steering_rear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_cc16_HEARTBEAT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::mav_cc16_HEARTBEAT_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "battery_voltage: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.battery_voltage);
    s << indent << "remote_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remote_control);
    s << indent << "drive_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drive_mode);
    s << indent << "rc_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.rc_velocity);
    s << indent << "rc_steering_front: ";
    Printer<float>::stream(s, indent + "  ", v.rc_steering_front);
    s << indent << "rc_steering_rear: ";
    Printer<float>::stream(s, indent + "  ", v.rc_steering_rear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_HEARTBEAT_H
