// Generated by gencpp from file drive_ros_msgs/mav_cc16_CONFIG_REQUEST_COUNT.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONFIG_REQUEST_COUNT_H
#define DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONFIG_REQUEST_COUNT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct mav_cc16_CONFIG_REQUEST_COUNT_
{
  typedef mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> Type;

  mav_cc16_CONFIG_REQUEST_COUNT_()
    : sysid(0)
    , compid(0)
    , dummy(0)  {
    }
  mav_cc16_CONFIG_REQUEST_COUNT_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , dummy(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _dummy_type;
  _dummy_type dummy;


    enum { ID = 192u };
 

  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> const> ConstPtr;

}; // struct mav_cc16_CONFIG_REQUEST_COUNT_

typedef ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<std::allocator<void> > mav_cc16_CONFIG_REQUEST_COUNT;

typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT > mav_cc16_CONFIG_REQUEST_COUNTPtr;
typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT const> mav_cc16_CONFIG_REQUEST_COUNTConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8bde82c47574bf9d3ab6bb685675a04";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8bde82c47574bf9ULL;
  static const uint64_t static_value2 = 0xd3ab6bb685675a04ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/mav_cc16_CONFIG_REQUEST_COUNT";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2017-06-12 22:33:47.453037\n\
# MESSAGE: CONFIG_REQUEST_COUNT\n\
# Description:Request quantity/id information of configs\n\
uint8 ID = 192\n\
uint8 sysid\n\
uint8 compid\n\
\n\
uint8 dummy\n\
";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.dummy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_cc16_CONFIG_REQUEST_COUNT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::mav_cc16_CONFIG_REQUEST_COUNT_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "dummy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dummy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONFIG_REQUEST_COUNT_H
