// Generated by gencpp from file drive_ros_msgs/mav_cc16_CONTROL_LIGHTS.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONTROL_LIGHTS_H
#define DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONTROL_LIGHTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct mav_cc16_CONTROL_LIGHTS_
{
  typedef mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> Type;

  mav_cc16_CONTROL_LIGHTS_()
    : sysid(0)
    , compid(0)
    , colors()  {
      colors.assign(0);
  }
  mav_cc16_CONTROL_LIGHTS_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , colors()  {
  (void)_alloc;
      colors.assign(0);
  }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef boost::array<uint32_t, 15>  _colors_type;
  _colors_type colors;


    enum { ID = 32u };
 

  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> const> ConstPtr;

}; // struct mav_cc16_CONTROL_LIGHTS_

typedef ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<std::allocator<void> > mav_cc16_CONTROL_LIGHTS;

typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS > mav_cc16_CONTROL_LIGHTSPtr;
typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS const> mav_cc16_CONTROL_LIGHTSConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d6b19f83df7d1d5d31de59ee6e1ece9";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d6b19f83df7d1d5ULL;
  static const uint64_t static_value2 = 0xd31de59ee6e1ece9ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/mav_cc16_CONTROL_LIGHTS";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2017-06-12 22:33:47.452797\n\
# MESSAGE: CONTROL_LIGHTS\n\
# Description:RGB lights\n\
uint8 ID = 32\n\
uint8 sysid\n\
uint8 compid\n\
\n\
uint32[15] colors   # Colors-4 bytes, r,g,b, nothing\n\
";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_cc16_CONTROL_LIGHTS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::mav_cc16_CONTROL_LIGHTS_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_CONTROL_LIGHTS_H
