// Generated by gencpp from file drive_ros_msgs/mav_cc16_COMMAND.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_COMMAND_H
#define DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct mav_cc16_COMMAND_
{
  typedef mav_cc16_COMMAND_<ContainerAllocator> Type;

  mav_cc16_COMMAND_()
    : sysid(0)
    , compid(0)
    , command(0)  {
    }
  mav_cc16_COMMAND_(const ContainerAllocator& _alloc)
    : sysid(0)
    , compid(0)
    , command(0)  {
  (void)_alloc;
    }



   typedef uint8_t _sysid_type;
  _sysid_type sysid;

   typedef uint8_t _compid_type;
  _compid_type compid;

   typedef uint8_t _command_type;
  _command_type command;


    enum { ID = 210u };
     enum { COMMAND_TYPE_IMU_CALI = 0u };
     enum { COMMAND_TYPE_SELF_TEST = 1u };
 

  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> const> ConstPtr;

}; // struct mav_cc16_COMMAND_

typedef ::drive_ros_msgs::mav_cc16_COMMAND_<std::allocator<void> > mav_cc16_COMMAND;

typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_COMMAND > mav_cc16_COMMANDPtr;
typedef boost::shared_ptr< ::drive_ros_msgs::mav_cc16_COMMAND const> mav_cc16_COMMANDConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be67c996d08c2861ab69974cb5883a21";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe67c996d08c2861ULL;
  static const uint64_t static_value2 = 0xab69974cb5883a21ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/mav_cc16_COMMAND";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Automatically Generated in 2017-06-12 22:33:47.453254\n\
# MESSAGE: COMMAND\n\
# Description:Command to perform\n\
uint8 ID = 210\n\
uint8 sysid\n\
uint8 compid\n\
\n\
uint8 command   # Command to perform (see COMMAND_TYPE ENUM)\n\
\n\
uint8 COMMAND_TYPE_IMU_CALI = 0           # Command: Perform IMU calibration\n\
uint8 COMMAND_TYPE_SELF_TEST = 1          # Command: Perform self-test of sensor and actor\n\
";
  }

  static const char* value(const ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sysid);
      stream.next(m.compid);
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_cc16_COMMAND_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::mav_cc16_COMMAND_<ContainerAllocator>& v)
  {
    s << indent << "sysid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sysid);
    s << indent << "compid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.compid);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_MAV_CC16_COMMAND_H
