// Generated by gencpp from file drive_ros_msgs/TimeCompare.msg
// DO NOT EDIT!


#ifndef DRIVE_ROS_MSGS_MESSAGE_TIMECOMPARE_H
#define DRIVE_ROS_MSGS_MESSAGE_TIMECOMPARE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drive_ros_msgs
{
template <class ContainerAllocator>
struct TimeCompare_
{
  typedef TimeCompare_<ContainerAllocator> Type;

  TimeCompare_()
    : header()
    , time_1()
    , time_2()
    , diff_time()  {
    }
  TimeCompare_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , time_1()
    , time_2()
    , diff_time()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _time_1_type;
  _time_1_type time_1;

   typedef ros::Time _time_2_type;
  _time_2_type time_2;

   typedef ros::Duration _diff_time_type;
  _diff_time_type diff_time;




  typedef boost::shared_ptr< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> const> ConstPtr;

}; // struct TimeCompare_

typedef ::drive_ros_msgs::TimeCompare_<std::allocator<void> > TimeCompare;

typedef boost::shared_ptr< ::drive_ros_msgs::TimeCompare > TimeComparePtr;
typedef boost::shared_ptr< ::drive_ros_msgs::TimeCompare const> TimeCompareConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drive_ros_msgs::TimeCompare_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drive_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'drive_ros_msgs': ['/home/nvidia/catkin_ws/src/drive_ros_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc58cdcc02bacea924ddf264cf2cf618";
  }

  static const char* value(const ::drive_ros_msgs::TimeCompare_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc58cdcc02bacea9ULL;
  static const uint64_t static_value2 = 0x24ddf264cf2cf618ULL;
};

template<class ContainerAllocator>
struct DataType< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drive_ros_msgs/TimeCompare";
  }

  static const char* value(const ::drive_ros_msgs::TimeCompare_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Debug Message\n\
Header header\n\
\n\
time time_1\n\
time time_2\n\
duration diff_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drive_ros_msgs::TimeCompare_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.time_1);
      stream.next(m.time_2);
      stream.next(m.diff_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TimeCompare_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drive_ros_msgs::TimeCompare_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drive_ros_msgs::TimeCompare_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "time_1: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_1);
    s << indent << "time_2: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time_2);
    s << indent << "diff_time: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.diff_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRIVE_ROS_MSGS_MESSAGE_TIMECOMPARE_H
