(cl:in-package drive_ros_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SYSID-VAL
          SYSID
          COMPID-VAL
          COMPID
          XACC-VAL
          XACC
          YACC-VAL
          YACC
          ZACC-VAL
          ZACC
          XGYRO-VAL
          XGYRO
          YGYRO-VAL
          YGYRO
          ZGYRO-VAL
          ZGYRO
          DIST_FRONT-VAL
          DIST_FRONT
          DIST_REAR-VAL
          DIST_REAR
          DIST_SIDE-VAL
          DIST_SIDE
          ODOM-VAL
          ODOM
          ODOM_ACCUMULATED-VAL
          ODOM_ACCUMULATED
          XMOTION_FRONT-VAL
          XMOTION_FRONT
          YMOTION_FRONT-VAL
          YMOTION_FRONT
          XMOTION_REAR-VAL
          XMOTION_REAR
          YMOTION_REAR-VAL
          YMOTION_REAR
          MOTION_FRONT_QUALITY-VAL
          MOTION_FRONT_QUALITY
          MOTION_REAR_QUALITY-VAL
          MOTION_REAR_QUALITY
          CURRENT_MOTOR-VAL
          CURRENT_MOTOR
          CURRENT_SERVO_FRONT-VAL
          CURRENT_SERVO_FRONT
          CURRENT_SERVO_REAR-VAL
          CURRENT_SERVO_REAR
          CURRENT_TOTAL-VAL
          CURRENT_TOTAL
          PWM_SERVO_FRONT-VAL
          PWM_SERVO_FRONT
          PWM_SERVO_REAR-VAL
          PWM_SERVO_REAR
          BATTERY_VOLTAGE-VAL
          BATTERY_VOLTAGE
          REMOTE_CONTROL-VAL
          REMOTE_CONTROL
          DRIVE_MODE-VAL
          DRIVE_MODE
))