# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drive_ros_msgs/mav_cc16_CONFIG_PARAM_SET_INT.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mav_cc16_CONFIG_PARAM_SET_INT(genpy.Message):
  _md5sum = "13a44efe541a5bf1e48949df36ecdb1d"
  _type = "drive_ros_msgs/mav_cc16_CONFIG_PARAM_SET_INT"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Automatically Generated in 2017-06-12 22:33:47.453203
# MESSAGE: CONFIG_PARAM_SET_INT
# Description:Set new config parameter int value
uint8 ID = 200
uint8 sysid
uint8 compid

uint8 config_id     # ID of the configuration set
uint8 param_id      # ID of the configuration parameter within the config set
int32 value         # New parameter value
"""
  # Pseudo-constants
  ID = 200

  __slots__ = ['sysid','compid','config_id','param_id','value']
  _slot_types = ['uint8','uint8','uint8','uint8','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sysid,compid,config_id,param_id,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mav_cc16_CONFIG_PARAM_SET_INT, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sysid is None:
        self.sysid = 0
      if self.compid is None:
        self.compid = 0
      if self.config_id is None:
        self.config_id = 0
      if self.param_id is None:
        self.param_id = 0
      if self.value is None:
        self.value = 0
    else:
      self.sysid = 0
      self.compid = 0
      self.config_id = 0
      self.param_id = 0
      self.value = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4Bi().pack(_x.sysid, _x.compid, _x.config_id, _x.param_id, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.sysid, _x.compid, _x.config_id, _x.param_id, _x.value,) = _get_struct_4Bi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4Bi().pack(_x.sysid, _x.compid, _x.config_id, _x.param_id, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.sysid, _x.compid, _x.config_id, _x.param_id, _x.value,) = _get_struct_4Bi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4Bi = None
def _get_struct_4Bi():
    global _struct_4Bi
    if _struct_4Bi is None:
        _struct_4Bi = struct.Struct("<4Bi")
    return _struct_4Bi
